# Generated by Django 2.1.3 on 2018-12-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20181203_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='match_length',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
