# Generated by Django 2.1.3 on 2018-12-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20181203_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='match_length',
            new_name='max_match_length',
        ),
    ]
