# Generated by Django 2.1.3 on 2018-12-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181203_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxmatchtype',
            name='max_match_length',
            field=models.IntegerField(default=60),
        ),
    ]
