# Generated by Django 2.1.5 on 2019-02-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_sandboxplayer_in_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandboxplayer',
            name='in_game',
        ),
    ]
