# Generated by Django 2.1.3 on 2018-11-27 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181127_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandboxplayer',
            name='player_group',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.SandboxPlayerGroup'),
        ),
    ]
