# Generated by Django 2.1.3 on 2018-11-29 11:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181127_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandboxplayer',
            name='player_group',
        ),
        migrations.AlterField(
            model_name='game',
            name='key',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sandboxmatch',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.SandboxMatchType'),
        ),
    ]
