# Generated by Django 2.1.3 on 2018-12-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_game_match_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
