# Generated by Django 2.1.5 on 2019-02-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_player_player_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxplayer',
            name='in_game',
            field=models.BooleanField(default=False),
        ),
    ]
